apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: odoo
  name: odoo
spec:
  type: LoadBalancer
  ports:
  - name: odoo
    port: 8069
    targetPort: 8069
  selector:
    io.kompose.service: odoo
